CREATE DATABASE alumnos;

USE alumnos;

CREATE TABLE estudiantes 
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_APELLIDO VARCHAR(80), 
    CORREO VARCHAR(80), 
    CURSO VARCHAR(40), 
    DNI VARCHAR(20), 
    CELULAR VARCHAR(20), 
    DIRECCION VARCHAR(100), 
    FECHA_REGISTRO DATE 
);